### ISSUE TITLE
Try and move Spark to a virtual account

### ISSUE THREAD

**Issue by mattsday** [CiscoUKIDCDev/ucsd-spark-plugin#6]
Don't know if it's possible, but it's stupid being in Storage!

**Comment by mattsday** [comment]
Bug when trying to do this - raised with API team...

```
2016-07-16 12:03:09,672 [pool-1-thread-35] WARN  executeOperation(ServiceProvider.java:757) - Error in operation
java.lang.NullPointerException
    at com.cloupia.service.cIM.inframgr.InfraPersistenceUtil.getCloudSummaryForOneCloud(InfraPersistenceUtil.java:1668)
    at com.cloupia.feature.configExplorer.converged.ConvergedStackBuilder.getVirtualSummaryList(ConvergedStackBuilder.java:500)
    at com.cloupia.feature.configExplorer.converged.ConvergedStackBuilder.populateVirtualComponents(ConvergedStackBuilder.java:473)
    at com.cloupia.feature.configExplorer.converged.ConvergedStackBuilder.buildStack(ConvergedStackBuilder.java:317)
    at com.cloupia.feature.configExplorer.converged.ConvergedStackBuilder.buildFromDBbySiteId(ConvergedStackBuilder.java:130)
    at com.cloupia.feature.configExplorer.converged.ConvergedInfraManagerImpl.userAPIGetAllStacksBySiteId(ConvergedInfraManagerImpl.java:36)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.cloupia.fw.services.provider.ServiceProvider.executeOperation(ServiceProvider.java:752)
    at com.cloupia.fw.services.provider.OperationRequestProcessor.run(OperationRequestProcessor.java:112)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by mattsday** [comment]
Not possible
